import turtle
turtle.setup(600,600)

turtle.speed(10.47)
# LOGO

turtle.setpos(0,-250)
turtle.pensize(8)
turtle.fillcolor('black')
turtle.begin_fill()
turtle.pencolor('gray')
turtle.circle(250)
turtle.end_fill()

turtle.pensize(3)
turtle.up()
turtle.setpos(0,-150)
turtle.down()
turtle.fillcolor('white')
turtle.begin_fill()
turtle.circle(150)
turtle.end_fill()

turtle.fillcolor('deepskyblue')
turtle.begin_fill()
turtle.circle(150,90)
turtle.left(90)
turtle.pensize(2)
turtle.pencolor('black')
turtle.forward(150)
turtle.left(90)
turtle.forward(150)
turtle.end_fill()
turtle.up()
turtle.setpos(-150,0)
turtle.down()
turtle.begin_fill()
turtle.pensize(3)
turtle.pencolor('gray')
turtle.circle(150,-90)
turtle.left(90)
turtle.pensize(2)
turtle.pencolor('black')
turtle.forward(150)
turtle.right(90)
turtle.forward(150)
turtle.end_fill()

# Letters

turtle.pensize(12)
turtle.pencolor('White')

# B

turtle.up()
turtle.setpos(0,0)
turtle.right(35)
turtle.forward(165)
turtle.right(5.2)
turtle.down()
turtle.forward(64)
turtle.right(90)
turtle.forward(35)
turtle.circle(-16,180)
turtle.forward(35)
turtle.right(180)
turtle.forward(35)
turtle.circle(-16,180)
turtle.forward(35)

# M

turtle.up()
turtle.setpos(-32,165)
turtle.setheading(90)
turtle.down()
turtle.forward(62)
turtle.setpos(0,180)
turtle.setpos(32,227)
turtle.right(180)
turtle.forward(62)

# W

turtle.up()
turtle.setpos(0,0)
turtle.setheading(52)
turtle.forward(228)
turtle.down()
turtle.right(170)
turtle.forward(65)
turtle.left(142)
turtle.forward(50)
turtle.right(142)
turtle.forward(50)
turtle.left(142)
turtle.forward(65)

turtle.hideturtle()
turtle.done()